inputSet:
  name: Build_Generate_my_Pipeline_configuration_1682577912514-push-trigger-input-set
  identifier: Build_Generate_my_Pipeline_configuration_1682577912514pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: test
  pipeline:
    identifier: Build_Generate_my_Pipeline_configuration_1682577912514
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
